spring.application.name=hello-spring
spring.datasource.url=jdbc:h2:tcp://localhost/~/test
spring.datasource.driver-class-name=org.h2.Driver
#jpa가 날리는 sql을 볼 수 있음.
spring.jpa.show-sql=true
#jpa는 기본적으로 객체를 보고 테이블을 자동생성하는데. 현재는 테이블을 만들어두고 작업하는것이여서 auto생성 none
spring.jpa.hibernate.ddl-auto=none
spring.datasource.username=sa